//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceHttp {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceHttp() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shared.Resources.ResourceHttp", typeof(ResourceHttp).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {phrase}, pois ocorreu um retorno inesperado ({code}) na requisição com o sistema &quot;{systemName}&quot;..
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {phrase}, pois ocorreu uma não conformidade na requisição com o sistema &quot;{systemName}&quot;..
        /// </summary>
        public static string InternalServerError500 {
            get {
                return ResourceManager.GetString("InternalServerError500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {phrase}, pois não foram encontrados no sistema &quot;{systemName}&quot;..
        /// </summary>
        public static string NoContent204 {
            get {
                return ResourceManager.GetString("NoContent204", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {phrase}, pois a requisição com o sistema &quot;{systemName}&quot; não foi encontrada..
        /// </summary>
        public static string NotFound404 {
            get {
                return ResourceManager.GetString("NotFound404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {phrase}, pois alguma requisição no servidor foi bloqueada!.
        /// </summary>
        public static string RequestRejected {
            get {
                return ResourceManager.GetString("RequestRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {phrase}, pois a requisição com o sistema &quot;{systemName}&quot; não foi autorizada..
        /// </summary>
        public static string Unauthorized401 {
            get {
                return ResourceManager.GetString("Unauthorized401", resourceCulture);
            }
        }
    }
}
